#!/bin/bash -l
#SBATCH --nodes 1
#SBATCH --ntasks 1
#SBATCH --cpus-per-task 1
#SBATCH --mem=1G
#SBATCH --time=72:00:00
#SBATCH --mail-user=XXXX@unil.ch
#SBATCH --error=snakemake.err

conda activate snakemake
module load singularity

snakemake --profile slurm --use-conda --use-singularity --unlock
snakemake --profile slurm --use-conda --use-singularity --rerun-incomplete --printshellcmds

## change your profile !
