#!/bin/bash -l
#SBATCH --nodes 1
#SBATCH --ntasks 1
#SBATCH --cpus-per-task 1
#SBATCH --mem=10G
#SBATCH --time=72:00:00
#SBATCH --mail-user=XXXX@unil.ch
#SBATCH --error=snakemake.err

conda activate snakemake
module load singularity

cd ann_snakemake/CarGra01/workflow_ann

snakemake --profile slurm --use-conda --use-singularity --unlock
snakemake --profile slurm --use-conda --use-singularity --rerun-incomplete --printshellcmds

## replace your profile !
