#parameters
asm: 'workflow_decontam/results/3_decontam/asm_decontaminated.fasta'
snakemake_dir_path: 'ann_snakemake/CarGra01/workflow_ann'
name: 'fCarGra01'
RNA_dir: 'raw_data/Carabus_granulatus/RNAseq'
adapters_file: "Trimmomatic/adapters/TruSeq2-PE.fa"
busco_phylum: 'arthropoda_odb10'

