#parameters

asm: '/path/to/assembly.fa'
snakemake_dir_path: '/path/to/workflow_ann'
name: 'fCarInt_v1'
busco_phylum: 'arthropoda_odb10'
samples:
  17_L4_001:
    type: 'paired-end'
    R1: '/path/to/RNAseq/17_L4_001_1.fastq.gz'
    R2: '/path/to/RNAseq/17_L4_001_2.fastq.gz'
  18_L4_001:
    type: 'single-end'
    R1: '/path/to/RNAseq/18_L4_001_1.fastq.gz'
